SELECT * FROM EMPLOYEES;
GRANT SELECT ON EMPLOYEES TO John;
GRANT CREATE TABLE TO PUBLIC;

GRANT SELECT ON CUSTOMERS TO ALICE WITH GRANT OPTION;

CREATE ROLE SALES_ROLE;
GRANT SELECT ON ORDERS TO SALES_ROLE;
GRANT INSERT ON CUSTOMERS TO SALES_ROLE;

