-- Add PUBLISH_YEAR column (integer type)
ALTER TABLE BOOKS
ADD PUBLISH_YEAR INT;

-- Add GENRE column (string type, e.g., VARCHAR(50))
ALTER TABLE BOOKS
ADD GENRE VARCHAR(50);

UPDATE BOOKS SET PUBLISH_YEAR = 1965, GENRE = 'Science Fiction' WHERE BOOK_ID = 1;
UPDATE BOOKS SET PUBLISH_YEAR = 1984, GENRE = 'Science Fiction' WHERE BOOK_ID = 2;
UPDATE BOOKS SET PUBLISH_YEAR = 2011, GENRE = 'Science Fiction' WHERE BOOK_ID = 3;
UPDATE BOOKS SET PUBLISH_YEAR = 1951, GENRE = 'Science Fiction' WHERE BOOK_ID = 4;
UPDATE BOOKS SET PUBLISH_YEAR = 2011, GENRE = 'Science Fiction' WHERE BOOK_ID = 5;
UPDATE BOOKS SET PUBLISH_YEAR = 1937, GENRE = 'Fantasy' WHERE BOOK_ID = 6;
UPDATE BOOKS SET PUBLISH_YEAR = 1997, GENRE = 'Fantasy' WHERE BOOK_ID = 7;
UPDATE BOOKS SET PUBLISH_YEAR = 2011, GENRE = 'Science Fiction' WHERE BOOK_ID = 8;
UPDATE BOOKS SET PUBLISH_YEAR = 1992, GENRE = 'Science Fiction' WHERE BOOK_ID = 9;
UPDATE BOOKS SET PUBLISH_YEAR = 2015, GENRE = 'Science Fiction' WHERE BOOK_ID = 10;

select * from books;

------Q1-------
SELECT * 
FROM BOOKS 
WHERE PUBLISH_YEAR > 2000 AND GENRE = 'Science Fiction' 
ORDER BY TITLE;

SELECT * 
FROM BOOKS 
WHERE PUBLISH_YEAR > 2000 OR GENRE = 'Science Fiction' 
ORDER BY TITLE;

SELECT * 
FROM BOOKS 
WHERE PUBLISH_YEAR > 2000 
HAVING GENRE = 'Science Fiction' 
ORDER BY TITLE;

SELECT * 
FROM BOOKS 
WHERE PUBLISH_YEAR > 2000 
GROUP BY GENRE = 'Science Fiction' 
ORDER BY TITLE;


------Q2-------
select * from employees;
select * from departments;
-- Add DEPARTMENT column (string type)
ALTER TABLE EMPLOYEES
ADD DEPARTMENT VARCHAR(50);

-- Add SALARY column (integer type)
ALTER TABLE EMPLOYEES
ADD SALARY INT;

SELECT * 
FROM EMPLOYEES 
WHERE SALARY >= 50000 AND DEPARTMENT = 'IT';


------Q3-------
select * from sales;

SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_SALES 
FROM SALES 
GROUP BY PRODUCT_ID 
HAVING SUM(AMOUNT) > 1000 
ORDER BY TOTAL_SALES DESC;


SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_SALES 
FROM SALES 
WHERE SUM(AMOUNT) > 1000 
GROUP BY PRODUCT_ID 
ORDER BY TOTAL_SALES DESC;

SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_SALES 
FROM SALES 
GROUP BY PRODUCT_ID 
WHERE SUM(AMOUNT) > 1000 
ORDER BY TOTAL_SALES DESC;

SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_SALES 
FROM SALES 
HAVING SUM(AMOUNT) > 1000 
GROUP BY PRODUCT_ID 
ORDER BY TOTAL_SALES DESC;

-------Q4--------
select * from customers where country='USA';

-------Q5--------
select * from orders;

SELECT CUSTOMER_ID, SUM(ORDER_TOTAL) AS TOTAL FROM ORDERS
WHERE EXTRACT(YEAR FROM ORDER_DATE) = 2025 GROUP BY
CUSTOMER_ID ORDER BY TOTAL DESC FETCH FIRST 5 ROWS ONLY;

SELECT TOP 5 CUSTOMER_ID, SUM(ORDER_TOTAL) AS TOTAL FROM
ORDERS WHERE YEAR(ORDER_DATE) = 2023 GROUP BY CUSTOMER_ID
ORDER BY TOTAL DESC;

SELECT CUSTOMER_ID, SUM(ORDER_TOTAL) AS TOTAL FROM ORDERS WHERE
TO_CHAR(ORDER_DATE, 'YYYY') = '2025' GROUP BY CUSTOMER_ID ORDER BY
TOTAL DESC LIMIT 5;

SELECT CUSTOMER_ID, SUM(ORDER_TOTAL) AS TOTAL FROM ORDERS WHERE
ORDER_DATE BETWEEN '2023-01-01' AND '2023-12-31' GROUP BY CUSTOMER_ID
ORDER BY TOTAL DESC ROWNUM <= 5;


-------Q6--------
select * from employees;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > 50000
ORDER BY HIRE_DATE;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > 50000
ORDER BY HIRE_DATE DESC;

SELECT FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY >= 50000
ORDER BY HIRE_DATE DESC;

--------Q7--------
select * from products;
ALTER TABLE products
ADD (
    category VARCHAR(50),
    price DECIMAL(10,2)
);

SELECT * 
FROM products 
WHERE category = 'Electronics' 
AND price BETWEEN 100 AND 500 
ORDER BY price;

SELECT product_name, price 
FROM products 
WHERE category = 'Electronics' 
AND price >= 100 AND price <= 500 
ORDER BY price DESC;

SELECT product_name, price 
FROM products 
WHERE category = 'Electronics' 
AND price BETWEEN 100 AND 500 
ORDER BY price DESC;

SELECT product_name 
FROM products 
WHERE category = 'Electronics' 
AND price > 100 AND price < 500 
ORDER BY price DESC;